The REST example uses Postman as client, not GWT. I need to use Spring Boot for server, and GWT for client. REST is fine if I dont have to add new libraries. (I want to avoid adding libraries like Domino to keep it simple and not worry about yet learning another tool, availability in my repo, and license).
Working in baby steps, I want to send a file from the GWT client to SpringBoot server.
Following the Spring docs https://spring.io/guides/gs/uploading-files/

I added a multipart file parameter, but then get a compile error

@WebServlet("/stockwatcher/greet")
public class GreetingServiceImpl extends RemoteServiceServlet implements GreetingService {

	public GreetingResponse greetServer(@RequestParam("file") MultipartFile file,
										RedirectAttributes redirectAttributes) throws IllegalArgumentException {
		// Verify that the input is valid.
		System.out.println("greetServer is called!");

I tried changing the GreetingService also but also get a compile error:

[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ StockWatcher-shared ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to C:\Users\User\Documents\Learn\GWT\Nalu\StockWatcher\StockWatcher-shared\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/User/Documents/Learn/GWT/Nalu/StockWatcher/StockWatcher-shared/src/main/java/stockwatcher/GreetingService.java:[11,38] cannot find symbol
  symbol:   class MultipartFile
  location: interface stockwatcher.GreetingService
[ERROR] /C:/Users/User/Documents/Learn/GWT/Nalu/StockWatcher/StockWatcher-shared/src/main/java/stockwatcher/GreetingService.java:[11,58] cannot find symbol
  symbol:   class RedirectAttributes
  location: interface stockwatcher.GreetingService
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for StockWatcher 1.0-SNAPSHOT:
[INFO]
[INFO] StockWatcher ....................................... SUCCESS [  0.075 s]
[INFO] StockWatcher-shared ................................ FAILURE [  0.835 s]
[INFO] StockWatcher-client ................................ SKIPPED
[INFO] StockWatcher-server ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.914 s
[INFO] Finished at: 2021-05-17T14:50:09-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project StockWatcher-shared: Compilation failure: Compilation failure:
[ERROR] /C:/Users/User/Documents/Learn/GWT/Nalu/StockWatcher/StockWatcher-shared/src/main/java/stockwatcher/GreetingService.java:[11,38] cannot find symbol
[ERROR]   symbol:   class MultipartFile
[ERROR]   location: interface stockwatcher.GreetingService
[ERROR] /C:/Users/User/Documents/Learn/GWT/Nalu/StockWatcher/StockWatcher-shared/src/main/java/stockwatcher/GreetingService.java:[11,58] cannot find symbol
[ERROR]   symbol:   class RedirectAttributes
[ERROR]   location: interface stockwatcher.GreetingService
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :StockWatcher-shared